sue:
  spring:
    quartz:
      cron: 0/5 * * * * ?

xxl:
  job:
    accessToken:
    executor:
      appname: demo
      ip:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
      port: 9966
    admin:
      addresses: http://127.0.0.1:8089/xxl-job-admin



