sue:
  spring:
    quartz:
      cron: 0/59 * * * * ?

xxl:
  job:
    accessToken: default_token
    executor:
      appname: xxljobtaskdemo
      ip:
      logpath: D:/job-handler
      logretentiondays: -1
      port: 9147 #${random.int[9000,10000]}
      address=:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
server:
  port: 9090


